## Álgebra lineal

In [2]:
import numpy as np

In [5]:
a = np.array([[3,2],[1,3]])
b = np.array([[2,2],[1,2]])
a

array([[3, 2],
       [1, 3]])

In [7]:
b

array([[2, 2],
       [1, 2]])

In [9]:
np.dot(a,b)

array([[ 8, 10],
       [ 5,  8]])

In [11]:
np.dot(b,a)

array([[ 8, 10],
       [ 5,  8]])

In [13]:
np.vdot(a,b)

17

In [15]:
a = np.arange(6).reshape(2,3)
b = np.arange(3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2]


In [17]:
np.inner(a,b)

array([ 5, 14])

Debido a:
0x0 + 1x1 + 2x2 = 5 
3x0 + 4x1 + 5x2 = 14

In [19]:
m = np.array([[2,3],[1,4]])
m

array([[2, 3],
       [1, 4]])

In [21]:
np.linalg.matrix_power(m,3)

array([[32, 93],
       [31, 94]])

In [23]:
np.dot(m,m)

array([[ 7, 18],
       [ 6, 19]])

### Valores propios ---- Determinantes y vectores propios

In [25]:
m = np.diag([4,3,2,1])
m

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

In [26]:
np.linalg.eig(m)

EigResult(eigenvalues=array([4., 3., 2., 1.]), eigenvectors=array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))

In [27]:
np.linalg.det(m)

24.000000000000004

In [30]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])