## Funciones lógicas

In [3]:
import numpy as np


In [5]:
a = np.array([2,3,4,5])
np.all(a < 20)

True

In [10]:
np.any(a <3)

True

In [12]:
np.logical_and(a > 2, a < 4)

array([False,  True, False, False])

In [17]:
b = np.allclose([1e10, 1e-7],[1.00001e10,1.00001e-7],rtol=0.00001)
b

True

In [23]:
np.array_equal(np.array([1,2,4]),np.array([1,2,4]))

True

In [25]:
np.array_equal(np.array([1,2,4]),np.array([1,22,4]))

False

In [27]:
np.greater_equal(np.array([1,2,4]),np.array([1,22,4]))

array([ True, False,  True])

## Funciones matemáticas

### Redondeo

In [79]:
a = 2.45435
a

2.45435

In [81]:
np.round(a,2)

2.45

In [82]:
array = np.array([1.435,13.1435,4.916])
np.round(array,2)

array([ 1.44, 13.14,  4.92])

In [84]:
np.floor(array)

array([ 1., 13.,  4.])

In [85]:
np.ceil(array)

array([ 2., 14.,  5.])

### Sumas y Productos

In [87]:
b = np.array([2,3,4])
np.prod(b)

24

In [88]:
b = np.array([[2,3,4],[2,2,2]])
np.prod(b)

192

In [89]:
np.prod(b,axis=0)

array([4, 6, 8])

In [91]:
np.prod(b,axis=1)

array([24,  8])

In [93]:
np.sum(b)

15

In [94]:
np.sum(b,axis=0)

array([4, 5, 6])

In [97]:
np.sum(b,axis=1)

array([9, 6])

### Exponentes y Logaritmos

In [99]:
np.exp(b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [100]:
np.power(np.e, b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [102]:
p = np.power(np.e,b)
p

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [103]:
np.log(p)

array([[2., 3., 4.],
       [2., 2., 2.]])

In [104]:
np.log10(b)

array([[0.30103   , 0.47712125, 0.60205999],
       [0.30103   , 0.30103   , 0.30103   ]])

In [105]:
np.log2(b)

array([[1.       , 1.5849625, 2.       ],
       [1.       , 1.       , 1.       ]])

In [106]:
np.log(0)

C:\Users\guille\AppData\Local\Temp\ipykernel_19620\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

### Operaciones aritméticas

In [107]:
a = np.array([[1,2,3,4],[4,3,2,1]])
b = np.array([4,3,2,1])

In [109]:
np.add(a,b)

array([[5, 5, 5, 5],
       [8, 6, 4, 2]])

In [110]:
np.subtract(a,b)

array([[-3, -1,  1,  3],
       [ 0,  0,  0,  0]])

In [111]:
np.multiply(a,b)

array([[ 4,  6,  6,  4],
       [16,  9,  4,  1]])

In [113]:
np.divide(a,b)

array([[0.25      , 0.66666667, 1.5       , 4.        ],
       [1.        , 1.        , 1.        , 1.        ]])

## Estadísticas

### Funciones relacionadas con el orden

In [29]:
a = np.array([1,2,5,4,10])
np.min(a)

1

In [31]:
np.max(a)

10

In [32]:
b = np.arange(12).reshape(3,4)

In [34]:
np.min(b, axis=0)

array([0, 1, 2, 3])

In [36]:
np.min(b, axis=1)

array([0, 4, 8])

In [39]:
np.max(b, axis=1)


array([ 3,  7, 11])

In [43]:
b = np.arange(0,101)

In [45]:
np.percentile(b, q = 11)

11.0

In [47]:
b = np.arange(10,400,2)
b

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110, 112,
       114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138,
       140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164,
       166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190,
       192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216,
       218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242,
       244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268,
       270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294,
       296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320,
       322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346,
       348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 37

In [54]:
np.percentile(b, q = 50)

204.0

In [56]:
np.quantile(b,q = 0.25)

107.0

### Medias y varianzas

In [59]:
b = np.arange(0,101)

In [61]:
np.mean(b)

50.0

In [62]:
# Meidan - valor central
np.median(b)

50.0

In [64]:
c = np.array([1,2,0,100,200,300,50])
np.mean(c)

93.28571428571429

In [66]:
np.median(c)

50.0

In [68]:
np.average(c)

93.28571428571429

In [72]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
np.mean(b)

5.5

In [75]:
np.mean(b, axis=0)

array([4.5, 5.5, 6.5])

In [77]:
np.std(b)

3.452052529534663

In [78]:
np.var(b,axis=1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])