## Manipulación arrays

In [2]:
import numpy as np

### Dimensiones del array

In [5]:
a = np.array([[1,2,3,4],[4,3,2,1]])
a.shape

(2, 4)

In [7]:
a.reshape((4,2))

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [9]:
a.ravel()

array([1, 2, 3, 4, 4, 3, 2, 1])

In [11]:
a.T

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

### Tipos de arrays


In [13]:
np.asarray([1,2,3,4],dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [15]:
np.asfarray([1,2,3,4])

array([1., 2., 3., 4.])

### Unión de arrays

In [22]:
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[4,3,2,1]])

print(a)
print(b)

[[1 2 3 4]
 [1 2 3 4]]
[[4 3 2 1]]


In [24]:
print(a.shape)
print(b.shape)

(2, 4)
(1, 4)


In [25]:
np.concatenate((a,b),axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])

In [29]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

### División de arrays

In [30]:
a = np.arange(0,20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.split(a, indices_or_sections=4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

### Añadir y eleminar elementos de un array

In [32]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [33]:
np.insert(a,obj=4, values=[5,6])

array([1, 2, 3, 4, 5, 6])

In [34]:
np.append(a,[7,8,9])

array([1, 2, 3, 4, 7, 8, 9])

In [35]:
np.delete(a,obj=3)

array([1, 2, 3])