## Cadenas


In [6]:
import numpy as np

In [8]:
a = np.array(['A','B','C'],dtype = np.str_)
b = np.array(['D','E','F'],dtype = np.str_)

np.char.add(a,b)

array(['AD', 'BE', 'CF'], dtype='<U2')

In [9]:
np.char.multiply(a,[2,3,4])

array(['AA', 'BBB', 'CCCC'], dtype='<U4')

In [12]:
nombres = np.array(['juan','pedro','maria'], dtype=np.str_)
nombres

array(['juan', 'pedro', 'maria'], dtype='<U5')

In [14]:
np.char.capitalize(nombres)

array(['Juan', 'Pedro', 'Maria'], dtype='<U5')

In [15]:
np.char.replace(nombres, 'mar', 'sof')

array(['juan', 'pedro', 'sofia'], dtype='<U5')

In [16]:
nombre = np.array(['Mi nombre es Guillermo Bastos'])
np.char.split(nombre, sep=' ')

array([list(['Mi', 'nombre', 'es', 'Guillermo', 'Bastos'])], dtype=object)

In [17]:
c = np.array(['        Hola', ' Adios     '])
np.char.strip(c)

array(['Hola', 'Adios'], dtype='<U12')

### Comparación

In [18]:
a = np.array(['A','B','C'], dtype=np.str_)
b = np.array(['D','E','F'], dtype=np.str_)

np.char.equal(a,b)

array([False, False, False])

In [20]:
np.char.not_equal(a,b)

array([ True,  True,  True])

In [21]:
np.char.greater_equal(a,b)

array([False, False, False])

### Información de cadenas

In [23]:
c = np.array(['Hola', 'Adios'])

np.char.endswith(c, suffix='ios')

array([False,  True])

In [25]:
np.char.startswith(c, prefix='Ad')

array([False,  True])

In [27]:
c = np.array(['Hola', 'adios'])

In [28]:
np.char.islower(c)

array([False,  True])

In [29]:
np.char.upper(c)

array(['HOLA', 'ADIOS'], dtype='<U5')

In [30]:
c = np.array(['Adios', 'Hola','123'])
np.char.isdigit(c)

array([False, False,  True])