## Operaciones

In [2]:
import numpy as np

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [9]:
np.identity(4, dtype= "int8")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [13]:
np.full(shape=(5,5), fill_value=5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
np.full(shape=(5,5), fill_value=[1,2,3,4,5])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

### Creación desde datos existentes

In [18]:
np.fromstring('1 2 3 4', sep=' ')

array([1., 2., 3., 4.])

In [20]:
datos = np.loadtxt('./datos.txt', delimiter=' ')
datos

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

## Rangos numéricos

In [22]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [25]:
np.linspace(start=1,stop=10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
np.linspace(start=1,stop=10, num=5, endpoint=False, retstep=True)

(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)

In [28]:
np.logspace(start=2, stop=3.5, num=10)

array([ 100.        ,  146.77992676,  215.443469  ,  316.22776602,
        464.15888336,  681.29206906, 1000.        , 1467.79926762,
       2154.43469003, 3162.27766017])

## Creación de matrices

In [31]:
a = np.eye(N = 4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.diag(a)

array([1., 1., 1., 1.])

In [34]:
np.diag(a, k = 1)

array([0., 0., 0.])

In [35]:
np.diagflat(v = [1,2,3,4,5], k= 0)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [36]:
np.tri(N = 5, M = 5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])